### ISSUE TITLE
site-packages/diffusers/image_processor.py:147: RuntimeWarning: invalid value encountered in cast   images = (images * 255).round().astype("uint8")

### ISSUE THREAD

**Issue by xiehuiyan** [THUDM/CogView3#14]
### System Info / 系統信息

  diffusers-0.31.0.dev0-py3-none-any.whl
cuda 12.2
python3.8

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

site-packages/diffusers/image_processor.py:147: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
  diffusers-0.31.0.dev0-py3-none-any.whl

### Expected behavior / 期待表现

done

**Comment by xiehuiyan** [comment]
done

**Comment by feng20001022** [comment]
> done
how did you solve this problem
